services:
  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    container_name: nginx
    user: "1000:1000"
    ports:
      - "80:8080"
    volumes:
      - "../test/server-entrypoint/nginx-k6.conf:/etc/nginx/nginx.conf:ro"
      - shared-sockets:/var/run/sockets:rw
    tmpfs:
      - /var/cache/nginx:uid=1000,gid=1000,mode=0755
      - /var/run:uid=1000,gid=1000,mode=0755
      - /tmp:uid=1000,gid=1000,mode=0755
    networks:
      - iamra_net

  database-mysql:
    image: mysql:8.0
    container_name: database-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iamra_course_test
    ports:
      - "3307:3306"
    networks:
      - iamra_net

  database-redis:
    image: redis:latest
    container_name: database-redis
    ports:
      - "6379:6379"
    networks:
      - iamra_net

  backend-api-user:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/user/Dockerfile.api-user
    container_name: backend-api-user
    volumes:
      - shared-sockets:/var/run/sockets:rw
    networks:
      - iamra_net

  backend-api-public:
    build:
      context: ../../
      dockerfile: docker/prod/backend-laravel/public/Dockerfile.api-public
    container_name: backend-api-public
    volumes:
      - shared-sockets:/var/run/sockets:rw
    networks:
      - iamra_net

  set-k6:
    image: grafana/k6:latest
    container_name: set-k6
    volumes:
      - "../../set-k6:/k6-scripts"
    command: tail -f /dev/null
    networks:
      - iamra_net

networks:
  iamra_net:
    driver: bridge

volumes:
  shared-sockets: